### ISSUE TITLE
Design a Twitter banner

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/brand#11]
Design a banner for use on Twitter and other social media sites.

The ration for the banner is 3:1. I've found that it's best to export a very large PNG image (e.g., 9000x3000) an allow Twitter to scale it down.

**Comment by ggrossetie** [comment]
It's done right ?

**Comment by mojavelinux** [comment]
We have a draft in place that will hold for now. We plan to apply project resources to contract a designer to make a proper professional brand package (post Asciidoctor 2.0). We need to go that route to accelerate this process. Once we have a better idea of that plan, we'll track it in this issue tracker.

**Comment by mojavelinux** [comment]
Let's call the first version done since we've been using it for over a year. There's always room for a new one.
