### ISSUE TITLE
Select colors for logo

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/brand#2]
Select colors for the logo, specifically a primary color. Apply it to the color version of the draft logo.

We're shooting for something that makes a bold statement. I've always personally been a fan of red, but I think pure red can be too harsh looking on screen. Therefore, I'd like to explore something in the carmine range. (See https://duckduckgo.com/?q=carmine+color&atb=v76-5_u&iax=images&ia=images)

What I like about carmine is that it sort of has a built-in gradient because it plays tricks on the eyes. It's noticeable, but also dynamic. I think that fits well with the message we want to portray.

**Comment by ahus1** [comment]
Once the colors are selected, it would be great to document the official RGB and CYMK codes (SVG only includes RGB, but CMYK is used for printing)

**Comment by mojavelinux** [comment]
Here are the colors I selected:

* charcoal (text and inverted color) - [#191919](http://www.color-hex.com/color/191919)
* carmine (accent and fill color) - [#e40046](http://www.color-hex.com/color/e40046)

**Comment by ahus1** [comment]
@mojavelinux - would you please also pick some CMYK color codes? This way you could print consistent stickers for notebooks... Thanks!

**Comment by mojavelinux** [comment]
I believe you can find the codes by following the color links in my comment. Do those work? (The next step will be to add these to the README).

**Comment by ahus1** [comment]
Sorry, everything that starts with a hash looks like a linked issue to me. I didn't expect them to link to color codes.
