### ISSUE TITLE
Extract each favicon "flavor" into a dedicated svg file

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/brand#5]
Disclaimer: I'm not a svg expert!

I guess this should be possible to extract each version of the favicon from the sprite but I couldn't figure it out. For practical reasons, I think we should provide each version as a single svg file, what do you think ?

For reference, my initial goal was to integrate the favicon on the browser extension: https://developer.mozilla.org/fr/Add-ons/WebExtensions/API/browserAction/setIcon

**Comment by mojavelinux** [comment]
I believe the existing sprite was just a proof. No doubt we should split them up as part of finalizing, so perhaps we can make this issue about finalizing the favicon. But to do that, we'll need to finalize the colors first.

I still think the lines in the favicon are a bit too exaggerated.

**Comment by mojavelinux** [comment]
I believe the existing sprite was just a proof. No doubt we should split them up as part of finalizing, so perhaps we can make this issue about finalizing the favicon. But to do that, we'll need to finalize the colors first.

I still think the lines in the favicon are a bit too exaggerated.

**Comment by ggrossetie** [comment]
> I still think the lines in the favicon are a bit too exaggerated.

Maybe this could help choose the right thickness:

![firefox](https://user-images.githubusercontent.com/333276/32690412-a2d76844-c6f6-11e7-8a93-c16d11af07ab.png)

![icon_extension](https://user-images.githubusercontent.com/333276/32690413-a3b72ace-c6f6-11e7-8f7f-5239bf3e0a9f.png)

**Comment by ggrossetie** [comment]
> I still think the lines in the favicon are a bit too exaggerated.

I'm not sure about that, this is the current svg as 16px: 
![16](https://user-images.githubusercontent.com/333276/33849441-de148d34-deb0-11e7-9716-7fbde04b4a5c.png)

Maybe we should simplify the design at 16px ? we could drop the round corners ? or just keep the A letter ?
For comparison here's the old favicon next to the new favicon:
![16](https://user-images.githubusercontent.com/333276/33849441-de148d34-deb0-11e7-9716-7fbde04b4a5c.png) ![asciidoc_icon_16](https://user-images.githubusercontent.com/333276/33849459-eec25a3a-deb0-11e7-85dc-94ce0122f53a.png)

The "React Developer Tools extension" icon looks pretty nice at 16px: 
![16-production](https://user-images.githubusercontent.com/333276/33849649-81475aea-deb1-11e7-92fa-b1f7e2cf6875.png)

![32-production](https://user-images.githubusercontent.com/333276/33849658-83e033e4-deb1-11e7-81cf-4407bc3675b7.png) ![48-production](https://user-images.githubusercontent.com/333276/33849660-84d1d028-deb1-11e7-94a6-de363a31a724.png) ![128-production](https://user-images.githubusercontent.com/333276/33849661-85f31174-deb1-11e7-830f-e8d19ad2d6a4.png)

Source: https://github.com/facebook/react-devtools/tree/master/shells/webextension/icons

**Comment by mojavelinux** [comment]
Now that the color has been selected, we can move forward with this one. I think the logo scales pretty well now, so let's see how it looks at 16px now.

@Mogztter for the chrome extension, I'm thinking using the carmine fill logo as "on" and a dimmed version of the bw fill logo as "off". Perhaps you can then use the regular color logo on the extensions page.

**Comment by ggrossetie** [comment]
Ok. I think we should also commit the 16x16 logo because we may need to tweak the thickness.

When you say the Carmine fill logo, you mean the background ? or the foreground ? I think we should drop the background in order to reduce the margins. The A letter will be more distinguishable.

**Comment by ggrossetie** [comment]
@mojavelinux Yep we should tweak the thickness, here's the result at 16px;

![logo-fill-color](https://user-images.githubusercontent.com/333276/39490350-e5ba596e-4d88-11e8-87b8-e0eab25d50a8.png)

**Comment by ggrossetie** [comment]
Here's another example where I've added 0.2pt thickness and removed the background:

![logo-fill-color1](https://user-images.githubusercontent.com/333276/39490696-f2f5f31c-4d89-11e8-9038-03680fdf24d0.png)

It's still very pixelated but at least we can see the A letter 😄

**Comment by ggrossetie** [comment]
On HDIP screen, using the `setIcon` function with an object helps: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/setIcon

![icon](https://user-images.githubusercontent.com/333276/44348514-ee04a200-a49a-11e8-9ad3-8fa88289908f.jpeg)

I'm also using a squared icon.

**Comment by mojavelinux** [comment]
I proposed a new set of icon-sized logos. (see https://github.com/asciidoctor/brand/pull/10) I think they are going to give us the sharpness we need.

@Mogztter Could you try it in the extension bar and see how it looks? Follow the instructions in the PR to make the 32x32 icon (which is 16x16 for HiDPI screens).

**Comment by mojavelinux** [comment]
> I'm also using a squared icon.

I think we should start with the rounded icon. We'll go to square if we find that just isn't working out.
