### ISSUE TITLE
Start using the new logo!

### ISSUE THREAD

**Issue by jirutka** [asciidoctor/brand#6]
@mojavelinux, will you ever start using this new logo? I don’t see it anywhere; there’s still the old one as a logo of the Asciidoctor GitHub organization and no logo at all at the webpage.

**Comment by ggrossetie** [comment]
I think we should also add the logo (with the name Asciidoctor) on the README. It gives the project a strong identity. Eg: https://github.com/chalk/chalk/blob/master/readme.md

**Comment by mojavelinux** [comment]
As soon as I have the resources to dedicate to put some project management in place for this project, the logo will be one of the first things addressed. The plan is to put that process in place in Q2 2018. It should address a lot of long-standing issues in the project.

**Comment by jirutka** [comment]
> to put some project management in place for this project

That’s just unbelievable. You need project management to put logo into readme, GH organization etc. I… I have no words… 😱

**Comment by mojavelinux** [comment]
I'm sorry you can't understand the importance of process.

**Comment by mojavelinux** [comment]
The process proved itself. Less than 1 month later and we're rolling out both the logo and 1.5.7.
