### ISSUE TITLE
Logo with name

### ISSUE THREAD

**Issue by ggrossetie** [asciidoctor/brand#8]
I think we need to have a logo with the name Asciidoctor but which font should we use ? Open Sans ? Noto Serif ?

**Comment by mojavelinux** [comment]
I had already identified a couple of fonts that I though fit well with the logo, but I don't think I ever got around to posting them.

Here's my list:

* quicksand
* comfortaa

The font doesn't necessary need to be open since it's for a brand, but I kind of feel like it should be.

**Comment by mojavelinux** [comment]
I'm leading more towards Quicksand.

Here are some other fonts I considered:

* Varela Round (only has 1 style)
* Jura
* Nunita

**Comment by ggrossetie** [comment]
We are "officially" using Comfortaa ?
